/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantallapricipal;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author holan
 */
public class food extends javax.swing.JFrame {

    /**
     * Creates new form food
     */
    public food() {
        initComponents();
        manzana.setText("59");
        platano.setText("89");
        naranja.setText("47");
        mango.setText("60");
        pina.setText("50");
        sandia.setText("30");
        uvas.setText("69");
        aguacate.setText("60");
        papaya.setText("43");
        pera.setText("57");
        kiwi.setText("41");
        lechuga.setText("5");
        cebolla.setText("46");
        apio.setText("14");
        brocoli.setText("31");
        ejotes.setText("30");
        tomates.setText("36");
        calabaza.setText("30");
        repollo.setText("22");
        esparragos.setText("27");
        zanahorias.setText("53");
        avena.setText("389");
        arroz.setText("130");
        maiz.setText("357");
        pan.setText("247");
        quinoa.setText("368");
        pavo.setText("198");
        puerco.setText("242");
        pescado.setText("208");
        pollo.setText("65");
        res.setText("250");
        camaron.setText("106");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manzana = new javax.swing.JCheckBox();
        platano = new javax.swing.JCheckBox();
        naranja = new javax.swing.JCheckBox();
        mango = new javax.swing.JCheckBox();
        pina = new javax.swing.JCheckBox();
        sandia = new javax.swing.JCheckBox();
        uvas = new javax.swing.JCheckBox();
        aguacate = new javax.swing.JCheckBox();
        papaya = new javax.swing.JCheckBox();
        pera = new javax.swing.JCheckBox();
        kiwi = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lechuga = new javax.swing.JCheckBox();
        cebolla = new javax.swing.JCheckBox();
        apio = new javax.swing.JCheckBox();
        brocoli = new javax.swing.JCheckBox();
        ejotes = new javax.swing.JCheckBox();
        tomates = new javax.swing.JCheckBox();
        calabaza = new javax.swing.JCheckBox();
        repollo = new javax.swing.JCheckBox();
        esparragos = new javax.swing.JCheckBox();
        recomlacha = new javax.swing.JCheckBox();
        zanahorias = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        avena = new javax.swing.JCheckBox();
        arroz = new javax.swing.JCheckBox();
        maiz = new javax.swing.JCheckBox();
        pan = new javax.swing.JCheckBox();
        quinoa = new javax.swing.JCheckBox();
        pavo = new javax.swing.JCheckBox();
        puerco = new javax.swing.JCheckBox();
        pescado = new javax.swing.JCheckBox();
        pollo = new javax.swing.JCheckBox();
        res = new javax.swing.JCheckBox();
        camaron = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        regreso = new javax.swing.JButton();
        calcularsi = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        panel2.setBackground(new java.awt.Color(13, 70, 113));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HEALTH TRACK ");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(38, 158, 230));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel2.setText("FRUITS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        manzana.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(manzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 54, -1, -1));

        platano.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(platano, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 79, -1, -1));

        naranja.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        naranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranjaActionPerformed(evt);
            }
        });
        jPanel3.add(naranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 107, -1, -1));

        mango.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        mango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoActionPerformed(evt);
            }
        });
        jPanel3.add(mango, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 132, -1, -1));

        pina.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(pina, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 157, -1, -1));

        sandia.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(sandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 182, -1, -1));

        uvas.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(uvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 207, -1, -1));

        aguacate.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(aguacate, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 232, -1, -1));

        papaya.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(papaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 257, -1, -1));

        pera.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(pera, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 288, -1, -1));

        kiwi.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel3.add(kiwi, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 313, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel5.setText("APPLE                             52 KAL");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 54, 167, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel6.setText("BANANA                       89KAL");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 82, 167, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel7.setText("ORANGE                       47 KAL ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 107, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel9.setText("MANGO                        60 KAL ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 132, 167, -1));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel10.setText("PINEAPPLE                   50 KAL");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 157, 167, -1));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel11.setText("WATERMELON          30KAL ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 182, 167, -1));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel12.setText("GRAPES                          69KAL");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 210, 167, -1));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel13.setText("AVOCADO                     160KAL");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 235, 167, -1));

        jLabel14.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel14.setText("PAPAYA                          43KAL");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 257, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel15.setText("PEAR                               57KAL");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 288, 167, -1));

        jLabel16.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel16.setText("KIWI                                 41KAL");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 316, 167, -1));

        jPanel4.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(38, 158, 230));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setText("VEGETABLES ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(62, 62, 62))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lechuga.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        cebolla.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        apio.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        brocoli.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        ejotes.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        tomates.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        calabaza.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        calabaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calabazaActionPerformed(evt);
            }
        });

        repollo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        esparragos.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        recomlacha.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        zanahorias.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel17.setText("LETTUCE                                        5 KAL ");

        jLabel18.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel18.setText("ONION                                          46 KAL");

        jLabel19.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel19.setText("CELERY                                           14 KAL");

        jLabel20.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel20.setText("BROCOLI                                       31 KAL");

        jLabel21.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel21.setText("GREEN BEANS                              30 KAL ");

        jLabel22.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel22.setText("TOMATOES                                   36 KAL");

        jLabel23.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel23.setText("PUMPKIN                                      30 KAL");

        jLabel24.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel24.setText("CABBAGE                                    22 KAL");

        jLabel25.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel25.setText("ASPARAGUS                                 27 KAL");

        jLabel26.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel26.setText("BETROOT                                      46 KAL");

        jLabel27.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel27.setText("CARROTS                                      53 KAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lechuga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cebolla, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brocoli, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ejotes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tomates, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calabaza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(repollo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(esparragos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(recomlacha, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(zanahorias, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lechuga)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cebolla)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apio)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brocoli)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejotes)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tomates)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calabaza)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(repollo)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esparragos)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recomlacha)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zanahorias)
                    .addComponent(jLabel27))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(38, 158, 230));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setText("CEREALS/GRAINS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        avena.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(avena, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        arroz.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(arroz, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        maiz.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        maiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maizActionPerformed(evt);
            }
        });
        jPanel5.add(maiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        pan.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        quinoa.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        quinoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quinoaActionPerformed(evt);
            }
        });
        jPanel5.add(quinoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        pavo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(pavo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        puerco.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(puerco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        pescado.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pescado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pescadoActionPerformed(evt);
            }
        });
        jPanel5.add(pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        pollo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(pollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        res.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        camaron.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jPanel5.add(camaron, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel28.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel28.setText("OATS                              389 KAL");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, -1));

        jLabel29.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel29.setText("RICE                                130 KAL ");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, -1));

        jLabel30.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel30.setText("CORN FLAKES               357 KAL");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, -1));

        jLabel31.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel31.setText("BREAD                            247 KAL");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        jLabel32.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel32.setText("QUINOA                         368 KAL");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, -1));

        jLabel33.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel33.setText("TURKEY                          198 KAL ");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, -1));

        jLabel34.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel34.setText("PORK LOIN                      242 KAL");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, -1));

        jLabel35.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel35.setText("CHICKEN                        165 KAL");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        jLabel36.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel36.setText("BEEF                                 250 KAL ");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, -1));

        jLabel37.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel37.setText("SHRIMP                            106 KAL ");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, -1));

        jLabel38.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel38.setText("FISH                                 208 KAL ");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/imagenvegetables-removebg-previe (2).png"))); // NOI18N

        regreso.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        regreso.setText("BACK ");
        regreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresoMouseClicked(evt);
            }
        });
        regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoActionPerformed(evt);
            }
        });

        calcularsi.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        calcularsi.setText("CALCULATE");
        calcularsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularsiMouseClicked(evt);
            }
        });

        resultado.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regreso)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calcularsi)
                        .addGap(18, 18, 18)
                        .addComponent(resultado))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regreso)
                        .addComponent(calcularsi)
                        .addComponent(resultado))
                    .addComponent(jLabel8))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naranjaActionPerformed

    private void mangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangoActionPerformed

    private void calabazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calabazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calabazaActionPerformed

    private void maizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maizActionPerformed

    private void quinoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quinoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quinoaActionPerformed

    private void regresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresoMouseClicked
        // TODO add your handling code here:
        // ESTE BOTON ES PARA REGRESAR A LA PAGINA PRINCIPAL 
        heart cora=new heart();//se crea un nuevo 
        cora.setVisible(true);//se crea desde arriba para que sea visible//
        dispose();//cerrar la ventana es necesario para hacer que la pantalla se minimice//
    }//GEN-LAST:event_regresoMouseClicked

    private void calcularsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularsiMouseClicked
        // TODO add your handling code here:
        int total = 0;
        

        JCheckBox[] alimentos = {
            manzana, platano, naranja, mango, pina, sandia, uvas, aguacate, papaya, pera, kiwi, lechuga, cebolla,
            apio, brocoli, ejotes, tomates, calabaza, repollo, esparragos, zanahorias,
            avena, arroz, maiz, pan, quinoa,
            pavo, puerco, pescado, pollo, res, camaron
        };

        for (JCheckBox alimento : alimentos) {
            if (alimento.isSelected()) {
                total += Integer.parseInt(alimento.getText());
            }
        }

        resultado.setText("CONSUMED CALORIES:" + total);

    }//GEN-LAST:event_calcularsiMouseClicked

    private void pescadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pescadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pescadoActionPerformed

    private void regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aguacate;
    private javax.swing.JCheckBox apio;
    private javax.swing.JCheckBox arroz;
    private javax.swing.JCheckBox avena;
    private javax.swing.JCheckBox brocoli;
    private javax.swing.JCheckBox calabaza;
    private javax.swing.JButton calcularsi;
    private javax.swing.JCheckBox camaron;
    private javax.swing.JCheckBox cebolla;
    private javax.swing.JCheckBox ejotes;
    private javax.swing.JCheckBox esparragos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JCheckBox kiwi;
    private javax.swing.JCheckBox lechuga;
    private javax.swing.JCheckBox maiz;
    private javax.swing.JCheckBox mango;
    private javax.swing.JCheckBox manzana;
    private javax.swing.JCheckBox naranja;
    private javax.swing.JCheckBox pan;
    private javax.swing.JPanel panel2;
    private javax.swing.JCheckBox papaya;
    private javax.swing.JCheckBox pavo;
    private javax.swing.JCheckBox pera;
    private javax.swing.JCheckBox pescado;
    private javax.swing.JCheckBox pina;
    private javax.swing.JCheckBox platano;
    private javax.swing.JCheckBox pollo;
    private javax.swing.JCheckBox puerco;
    private javax.swing.JCheckBox quinoa;
    private javax.swing.JCheckBox recomlacha;
    private javax.swing.JButton regreso;
    private javax.swing.JCheckBox repollo;
    private javax.swing.JCheckBox res;
    private javax.swing.JLabel resultado;
    private javax.swing.JCheckBox sandia;
    private javax.swing.JCheckBox tomates;
    private javax.swing.JCheckBox uvas;
    private javax.swing.JCheckBox zanahorias;
    // End of variables declaration//GEN-END:variables
}
