/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantallapricipal;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author holan
 */
public class food extends javax.swing.JFrame {

    /**
     * Creates new form food
     */
    public food() {
        initComponents();
        manzana.setText(" manzna   59");
        platano.setText(" platano  89");
        naranja.setText("naranja 47");
        mango.setText("60");
        pina.setText("50");
        sandia.setText("30");
        uvas.setText("69");
        aguacate.setText("60");
        papaya.setText("43");
        pera.setText("57");
        kiwi.setText("41");
        lechuga.setText("5");
        cebolla.setText("46");
        apio.setText("14");
        brocoli.setText("31");
        ejotes.setText("30");
        tomates.setText("36");
        calabaza.setText("30");
        repollo.setText("22");
        esparragos.setText("27");
        zanahorias.setText("53");
        avena.setText("389");
        arroz.setText("130");
        maiz.setText("357");
        pan.setText("247");
        quinoa.setText("368");
        pavo.setText("198");
        puerco.setText("242");
        pescado.setText("208");
        pollo.setText("65");
        res.setText("250");
        camaron.setText("106");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manzana = new javax.swing.JCheckBox();
        platano = new javax.swing.JCheckBox();
        naranja = new javax.swing.JCheckBox();
        mango = new javax.swing.JCheckBox();
        pina = new javax.swing.JCheckBox();
        sandia = new javax.swing.JCheckBox();
        uvas = new javax.swing.JCheckBox();
        aguacate = new javax.swing.JCheckBox();
        papaya = new javax.swing.JCheckBox();
        pera = new javax.swing.JCheckBox();
        kiwi = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lechuga = new javax.swing.JCheckBox();
        cebolla = new javax.swing.JCheckBox();
        apio = new javax.swing.JCheckBox();
        brocoli = new javax.swing.JCheckBox();
        ejotes = new javax.swing.JCheckBox();
        tomates = new javax.swing.JCheckBox();
        calabaza = new javax.swing.JCheckBox();
        repollo = new javax.swing.JCheckBox();
        esparragos = new javax.swing.JCheckBox();
        recomlacha = new javax.swing.JCheckBox();
        zanahorias = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        avena = new javax.swing.JCheckBox();
        arroz = new javax.swing.JCheckBox();
        maiz = new javax.swing.JCheckBox();
        pan = new javax.swing.JCheckBox();
        quinoa = new javax.swing.JCheckBox();
        pavo = new javax.swing.JCheckBox();
        puerco = new javax.swing.JCheckBox();
        pescado = new javax.swing.JCheckBox();
        pollo = new javax.swing.JCheckBox();
        res = new javax.swing.JCheckBox();
        camaron = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        regreso = new javax.swing.JButton();
        calcularsi = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        panel2.setBackground(new java.awt.Color(13, 70, 113));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HEALTH TRACK ");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(38, 158, 230));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel2.setText("FRUITS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        manzana.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        manzana.setText("APPLE                             52 KAL");

        platano.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        platano.setText("BANANA                         89KAL");

        naranja.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        naranja.setText("ORANGE                           47 KAL ");
        naranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranjaActionPerformed(evt);
            }
        });

        mango.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        mango.setText("MANGO                           60 KAL ");
        mango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoActionPerformed(evt);
            }
        });

        pina.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pina.setText("PINEAPPLE                      50 KAL");

        sandia.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        sandia.setText("WATERMELON               30KAL ");

        uvas.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        uvas.setText("GRAPES                            69KAL");

        aguacate.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        aguacate.setText("AVOCADO                       160KAL");

        papaya.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        papaya.setText("PAPAYA                          43KAL");

        pera.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pera.setText("PEAR                                 57KAL");

        kiwi.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        kiwi.setText("KIWI                                    41KAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(platano)
                    .addComponent(manzana)
                    .addComponent(naranja)
                    .addComponent(mango)
                    .addComponent(pina)
                    .addComponent(sandia)
                    .addComponent(uvas)
                    .addComponent(aguacate)
                    .addComponent(papaya)
                    .addComponent(pera)
                    .addComponent(kiwi)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manzana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naranja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sandia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uvas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aguacate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(papaya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kiwi)
                .addGap(48, 48, 48))
        );

        jPanel4.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(38, 158, 230));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setText("VEGETABLES ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(62, 62, 62))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lechuga.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        lechuga.setText("LETTUCE                                        5 KAL ");

        cebolla.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        cebolla.setText("ONION                                          46 KAL");

        apio.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        apio.setText("CELERY                                           14 KAL");

        brocoli.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        brocoli.setText("BROCOLI                                       31 KAL");

        ejotes.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        ejotes.setText("GREEN BEANS                              30 KAL ");

        tomates.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        tomates.setText("TOMATOES                                   36 KAL");

        calabaza.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        calabaza.setText("PUMPKIN                                      30 KAL");
        calabaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calabazaActionPerformed(evt);
            }
        });

        repollo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        repollo.setText("CABBAGE                                    22 KAL");

        esparragos.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        esparragos.setText("ASPARAGUS                                 27 KAL");

        recomlacha.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        recomlacha.setText("BETROOT                               46 KAL");

        zanahorias.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        zanahorias.setText("CARROTS                                      53 KAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lechuga)
                    .addComponent(cebolla)
                    .addComponent(apio)
                    .addComponent(zanahorias)
                    .addComponent(recomlacha)
                    .addComponent(repollo)
                    .addComponent(calabaza)
                    .addComponent(tomates)
                    .addComponent(ejotes)
                    .addComponent(brocoli)
                    .addComponent(esparragos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lechuga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cebolla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brocoli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tomates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calabaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esparragos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recomlacha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zanahorias)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(38, 158, 230));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setText("CEREALS/GRAINS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        avena.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        avena.setText("OATS                              389 KAL");
        jPanel5.add(avena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        arroz.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        arroz.setText("RICE                                130 KAL ");
        jPanel5.add(arroz, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        maiz.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        maiz.setText("CORN FLAKES               357 KAL");
        maiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maizActionPerformed(evt);
            }
        });
        jPanel5.add(maiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        pan.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pan.setText("BREAD                            247 KAL");
        jPanel5.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        quinoa.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        quinoa.setText("QUINOA                         368 KAL");
        quinoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quinoaActionPerformed(evt);
            }
        });
        jPanel5.add(quinoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        pavo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pavo.setText("TURKEY                          198 KAL ");
        jPanel5.add(pavo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        puerco.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        puerco.setText("PORK LOIN                      242 KAL");
        jPanel5.add(puerco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        pescado.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pescado.setText("FISH                                 208 KAL ");
        jPanel5.add(pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        pollo.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        pollo.setText("CHICKEN                        165 KAL");
        jPanel5.add(pollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        res.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        res.setText("BEEF                                 250 KAL ");
        jPanel5.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        camaron.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        camaron.setText("SHRIMP                            106 KAL ");
        jPanel5.add(camaron, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/imagenvegetables-removebg-previe (2).png"))); // NOI18N

        regreso.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        regreso.setText("BACK ");
        regreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresoMouseClicked(evt);
            }
        });

        calcularsi.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        calcularsi.setText("CALCULATE");
        calcularsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularsiMouseClicked(evt);
            }
        });

        resultado.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regreso)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calcularsi)
                        .addGap(18, 18, 18)
                        .addComponent(resultado))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regreso)
                            .addComponent(calcularsi)
                            .addComponent(resultado))
                        .addGap(54, 54, 54))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naranjaActionPerformed

    private void mangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangoActionPerformed

    private void calabazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calabazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calabazaActionPerformed

    private void maizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maizActionPerformed

    private void quinoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quinoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quinoaActionPerformed

    private void regresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresoMouseClicked
        // TODO add your handling code here:
        // ESTE BOTON ES PARA REGRESAR A LA PAGINA PRINCIPAL 
        heart cora=new heart();//se crea un nuevo 
        cora.setVisible(true);//se crea desde arriba para que sea visible//
        dispose();//cerrar la ventana es necesario para hacer que la pantalla se minimice//
    }//GEN-LAST:event_regresoMouseClicked

    private void calcularsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularsiMouseClicked
        // TODO add your handling code here:
        int total = 0;
        

        JCheckBox[] alimentos = {
            manzana, platano, naranja, mango, pina, sandia, uvas, aguacate, papaya, pera, kiwi, lechuga, cebolla,
            apio, brocoli, ejotes, tomates, calabaza, repollo, esparragos, zanahorias,
            avena, arroz, maiz, pan, quinoa,
            pavo, puerco, pescado, pollo, res, camaron
        };

        for (JCheckBox alimento : alimentos) {
            if (alimento.isSelected()) {
                total += Integer.parseInt(alimento.getText());
            }
        }

        resultado.setText("CONSUMED CALORIES:" + total);

    }//GEN-LAST:event_calcularsiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aguacate;
    private javax.swing.JCheckBox apio;
    private javax.swing.JCheckBox arroz;
    private javax.swing.JCheckBox avena;
    private javax.swing.JCheckBox brocoli;
    private javax.swing.JCheckBox calabaza;
    private javax.swing.JButton calcularsi;
    private javax.swing.JCheckBox camaron;
    private javax.swing.JCheckBox cebolla;
    private javax.swing.JCheckBox ejotes;
    private javax.swing.JCheckBox esparragos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JCheckBox kiwi;
    private javax.swing.JCheckBox lechuga;
    private javax.swing.JCheckBox maiz;
    private javax.swing.JCheckBox mango;
    private javax.swing.JCheckBox manzana;
    private javax.swing.JCheckBox naranja;
    private javax.swing.JCheckBox pan;
    private javax.swing.JPanel panel2;
    private javax.swing.JCheckBox papaya;
    private javax.swing.JCheckBox pavo;
    private javax.swing.JCheckBox pera;
    private javax.swing.JCheckBox pescado;
    private javax.swing.JCheckBox pina;
    private javax.swing.JCheckBox platano;
    private javax.swing.JCheckBox pollo;
    private javax.swing.JCheckBox puerco;
    private javax.swing.JCheckBox quinoa;
    private javax.swing.JCheckBox recomlacha;
    private javax.swing.JButton regreso;
    private javax.swing.JCheckBox repollo;
    private javax.swing.JCheckBox res;
    private javax.swing.JLabel resultado;
    private javax.swing.JCheckBox sandia;
    private javax.swing.JCheckBox tomates;
    private javax.swing.JCheckBox uvas;
    private javax.swing.JCheckBox zanahorias;
    // End of variables declaration//GEN-END:variables
}
