/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantallapricipal;

/**
 *
 * @author usuario
 */
public class List extends javax.swing.JFrame {

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        underground = new javax.swing.JPanel();
        izquierdo1 = new javax.swing.JPanel();
        izquierdo2 = new javax.swing.JPanel();
        derecho1 = new javax.swing.JPanel();
        derecho2 = new javax.swing.JPanel();
        backbutton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        E1 = new javax.swing.JPanel();
        e2 = new javax.swing.JLabel();
        C1 = new javax.swing.JPanel();
        c1 = new javax.swing.JLabel();
        N1 = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        gym = new javax.swing.JLabel();

        back.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        underground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izquierdo1.setBackground(new java.awt.Color(0, 153, 153));

        izquierdo2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout izquierdo2Layout = new javax.swing.GroupLayout(izquierdo2);
        izquierdo2.setLayout(izquierdo2Layout);
        izquierdo2Layout.setHorizontalGroup(
            izquierdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        izquierdo2Layout.setVerticalGroup(
            izquierdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout izquierdo1Layout = new javax.swing.GroupLayout(izquierdo1);
        izquierdo1.setLayout(izquierdo1Layout);
        izquierdo1Layout.setHorizontalGroup(
            izquierdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izquierdo1Layout.createSequentialGroup()
                .addComponent(izquierdo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        izquierdo1Layout.setVerticalGroup(
            izquierdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izquierdo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        underground.add(izquierdo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 500));

        derecho1.setBackground(new java.awt.Color(0, 153, 153));

        derecho2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout derecho2Layout = new javax.swing.GroupLayout(derecho2);
        derecho2.setLayout(derecho2Layout);
        derecho2Layout.setHorizontalGroup(
            derecho2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        derecho2Layout.setVerticalGroup(
            derecho2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        backbutton.setBackground(new java.awt.Color(204, 204, 255));
        backbutton.setText("back");
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout derecho1Layout = new javax.swing.GroupLayout(derecho1);
        derecho1.setLayout(derecho1Layout);
        derecho1Layout.setHorizontalGroup(
            derecho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derecho1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(derecho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(derecho2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        derecho1Layout.setVerticalGroup(
            derecho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derecho1Layout.createSequentialGroup()
                .addComponent(derecho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backbutton)
                .addContainerGap())
        );

        underground.add(derecho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 100, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/logosinfondo.png"))); // NOI18N
        logo.setText("jLabel1");
        underground.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 140));

        E1.setBackground(new java.awt.Color(71, 153, 239));

        e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/cuerda.png"))); // NOI18N
        e2.setText("jLabel1");
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout E1Layout = new javax.swing.GroupLayout(E1);
        E1.setLayout(E1Layout);
        E1Layout.setHorizontalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, E1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        E1Layout.setVerticalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, E1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        underground.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        C1.setBackground(new java.awt.Color(71, 153, 239));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/bicicleta.png"))); // NOI18N
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout C1Layout = new javax.swing.GroupLayout(C1);
        C1.setLayout(C1Layout);
        C1Layout.setHorizontalGroup(
            C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        C1Layout.setVerticalGroup(
            C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        underground.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        N1.setBackground(new java.awt.Color(71, 153, 239));

        n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/natacion.png"))); // NOI18N
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout N1Layout = new javax.swing.GroupLayout(N1);
        N1.setLayout(N1Layout);
        N1Layout.setHorizontalGroup(
            N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1Layout.createSequentialGroup()
                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        N1Layout.setVerticalGroup(
            N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        underground.add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 110, -1));

        man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/man.png"))); // NOI18N
        man.setText("jLabel1");
        underground.add(man, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 440, 500));

        gym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/WhatsApp Image 2025-07-03 at 10.47.23 PM.jpeg"))); // NOI18N
        gym.setText("jLabel1");
        underground.add(gym, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 540, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(underground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(underground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseClicked

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_n1MouseClicked

    private void e2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e2MouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonActionPerformed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        
        //regreso del boton
    }//GEN-LAST:event_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel C1;
    private javax.swing.JPanel E1;
    private javax.swing.JPanel N1;
    private javax.swing.JButton back;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel c1;
    private javax.swing.JPanel derecho1;
    private javax.swing.JPanel derecho2;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel gym;
    private javax.swing.JPanel izquierdo1;
    private javax.swing.JPanel izquierdo2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel man;
    private javax.swing.JLabel n1;
    private javax.swing.JPanel underground;
    // End of variables declaration//GEN-END:variables
}
