/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantallapricipal;

import javax.swing.JFrame;
import java.awt.Color;
/**
 *
 * @author usuario
 */
public class stick_man extends javax.swing.JFrame {

    /**
     * Creates new form stick_man
     */
    public stick_man() {
        initComponents();
        // Dentro del constructor o un método de tu JFrame
boolean buenosHabitos = true; // o false, según los datos

// Cambia el fondo del panel principal
if (buenosHabitos) {
    getContentPane().setBackground(Color.GREEN);
} else {
    getContentPane().setBackground(Color.RED);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        luna = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        change = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 170, 170));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        luna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/lunal (1).png"))); // NOI18N
        luna.setText("jLabel1");
        luna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lunaMouseClicked(evt);
            }
        });
        jPanel1.add(luna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 440, 450));

        head.setBackground(new java.awt.Color(13, 70, 113));
        head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Calisto MT", 3, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("SLEEP QUALITY");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        head.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 190, 54));

        jPanel1.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 586, -1));

        change.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        change.setText("change\n");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
        heart sueno = new heart ();
        sueno.setVisible(true);
        dispose();
    }//GEN-LAST:event_nameMouseClicked

    private void lunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lunaMouseClicked
        // TODO add your handling code here:
        int calidadSueño = 6;
int alimentacion = 8;
int ejercicio = 7;

// Evaluación de la salud y cambio de color
if (calidadSueño >= 7 && alimentacion >= 7 && ejercicio >= 7) {
    jPanel1.setBackground(new java.awt.Color(0, 128, 0)); // Verde (buena salud)
} else if (calidadSueño >= 4 && alimentacion >= 4 && ejercicio >= 4) {
    jPanel1.setBackground(new java.awt.Color(255, 215, 0)); // Amarillo (regular)
} else {
    jPanel1.setBackground(new java.awt.Color(178, 34, 34)); // Rojo (mala salud)
}
        
        
    }//GEN-LAST:event_lunaMouseClicked

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        
         stick_man luna = new stick_man();
    luna.setVisible(true);
    }//GEN-LAST:event_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stick_man.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stick_man.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stick_man.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stick_man.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stick_man().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JPanel head;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel luna;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
